[versions]
kotlin = "2.2.21"
kotlin-logging = "7.0.13"
kotlinx-serialization = "1.9.0"
ktor = "3.3.3"
koin = "4.1.1"
slf4j = "2.0.17"
logback = "1.5.19"
javassist = "3.30.2-GA"
jooq = "3.20.9"
liquibase = "4.33.0"
liquibase-slf4j = "5.1.0"
postgresql = "42.7.7"
kobby = "5.3.0"
apollo = "4.3.3"

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kobby = { id = "io.github.ermadmi78.kobby", version.ref = "kobby" }
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }

[libraries]
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlin-logging" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
javassist = { group = "org.javassist", name = "javassist", version.ref = "javassist" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }

jooq-codegen = { group = "org.jooq", name = "jooq-codegen", version.ref = "jooq" }
jooq-meta = { group = "org.jooq", name = "jooq-meta", version.ref = "jooq" }
jooq-meta-extension-liquibase = { group = "org.jooq", name = "jooq-meta-extensions-liquibase", version.ref = "jooq" }
jooq-kotlin = { group = "org.jooq", name = "jooq-kotlin", version.ref = "jooq" }

liquibase = { group = "org.liquibase", name = "liquibase-core", version.ref = "liquibase" }
liquibase-slf4j = { group = "com.mattbertolini", name = "liquibase-slf4j", version.ref = "liquibase-slf4j" }

ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }

ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-server-config-yaml = { group = "io.ktor", name = "ktor-server-config-yaml", version.ref = "ktor" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }

ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

koin-ktor = { group = "io.insert-koin", name = "koin-ktor", version.ref = "koin" }
koin-logger-slf4j = { group = "io.insert-koin", name = "koin-logger-slf4j", version.ref = "koin" }

apollo-runtime = { group = "com.apollographql.apollo", name = "apollo-runtime", version.ref = "apollo" }
