ktor:
  deployment:
    port: 8080
  application:
    modules:
      - ru.alexredby.stocktaking.ApplicationKt.module

database:
  host: localhost
  port: 5432
  name: stocktaking
  user: stocktaking
  password: ${DB_PASSWORD}
